site_name: Xenoglot
site_description: Xenoglot seamlessly masters languages and locales, empowering developers to integrate multilingual capabilities into their applications with ease.
site_author: Teodor Grigor (teogor)
site_dir: build/docs/redesigned-garbanzo
site_url: https://github.com/teogor/redesigned-garbanzo
edit_uri: tree/main/docs/

docs_dir: docs

# Repository
repo_name: redesigned-garbanzo
repo_url: https://github.com/teogor/redesigned-garbanzo

# Copyright
copyright: Copyright &copy; 2023 Teodor Grigor (Teogor)

# Navigation
nav:
  - 'Overview': index.md
  - 'Releases': releases.md
  - 'API Reference': api-reference.md
  - 'Mapping': mapping.md
  - 'Version Catalog': version-catalog.md
  - 'BoM': bom/versions.md
  - 'Sponsor': sponsor.md
  - 'Security': security.md

# Configuration
theme:
  name: material
  language: en

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto
    code: JetBrains Mono

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
     - content.code.select
     - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
      minify_css: true

extra:
  analytics:
    provider: google
    property: G-XN9N2SV8QZ

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
